import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import TopBar from '@/components/topBar'
import PostTabPanel from '@/components/postTabPanel'
import ButtonAppBar from '@/components/examples/app_bar'
import ElevateAppBar from '@/components/examples/elevateAppbar'
import { useState, useEffect } from 'react'
import Box from '@mui/material/Box'
import useSWR from "swr";
import axios from 'axios';
import {backend} from '@/query.config';
import SearchResults from '@/components/searchResults'


axios.defaults.withCredentials = true

export default function HomePage() {
  const [ isLoggedIn, setIsLoggedIn ] = useState(false)
  const [ username, setUsername ] = useState("abhinav")
  const [ userDisplayName, setUserDisplayName ] = useState("Abhinav")
  const [ userId, setUserId ] = useState("7498")
  const [ showSearchResults, setShowSearchResults ] = useState(false)
  const [ options, setOptions ] = useState([])
  const [ orderBy, setOrderBy ] = useState("time")
  const [ searchInputValue, setSearchInputValue ] = useState("")
  const [ selectedList, setSelectedList ] = useState([])

  const getSelected = () => {
    return selectedList
  }

  useEffect(() => {
    const setter = async () => {
      try {
        const data = (await axios.get(`${backend}/login`)).data;
        if (data.status == 'OK'){
          setIsLoggedIn(data.isLoggedIn);
          setUsername(data.username);
          setUserDisplayName(data.displayName);
          setUserId(data.userId);
        } else {
          setIsLoggedIn(false);
        }
      } catch (e) {

      }
    }

    setter();
  });

  return (
    <>
      <TopBar isLoggedIn={isLoggedIn} username={username} userDisplayName={userDisplayName} userId={userId} setIsLoggedIn={setIsLoggedIn} selected={selectedList} setSelected={setSelectedList} setShowSearchResults={setShowSearchResults}
        options={options} setOptions={setOptions} searchInputValue={searchInputValue} setSearchInputValue={setSearchInputValue}
        orderBy={orderBy} setOrderBy={setOrderBy} showSearchBar
      />
      <Box display="flex">
        <Box flexGrow={1} />
          <Box sx={{display: "flex", width: {xs: "95%", sm: "85%", md: "75%", lg: "65%", xl: "55%"}, maxWidth: "max-content"}}>
            {
              showSearchResults
              &&
              <SearchResults selectedList={selectedList} setSelectedList={setSelectedList} options={options}
                searchInputValue={searchInputValue} setSearchInputValue={setSearchInputValue} setOptions={setOptions}
                orderBy={orderBy} setShowSearchResults={setShowSearchResults}
              />
              ||
              <PostTabPanel isLoggedIn={isLoggedIn} username={username} userDisplayName={userDisplayName} userId={userId}/>
            }
          </Box>
        <Box flexGrow={1} />
      </Box>
    </>
  )
}


// export function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>pages/index.js</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{' '}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>

//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//           <div className={styles.thirteen}>
//             <Image
//               src="/thirteen.svg"
//               alt="13"
//               width={40}
//               height={31}
//               priority
//             />
//           </div>
//         </div>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   )
// }
